---
- name: Join Worker Node to Kubernetes Cluster
  hosts: worker
  become: yes
  tasks:

    - name: Install kubeadm, kubelet and kubectl on worker
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Get join command from control plane
      command: kubeadm token create --print-join-command
      delegate_to: control-plane
      register: join_command_raw

    - name: Join the worker node
      shell: "{{ join_command_raw.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf